version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
      - '12345:12345'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - JMX_PORT=12345
    depends_on:
      - zookeeper
  kafdrop:
    image: 'docker.io/obsidiandynamics/kafdrop:3.27.0'
    ports:
      - '9000:9000'
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
  kafka_manager:
   image: hlebalbau/kafka-manager:stable
   ports:
     - '9001:9000'
   environment:
     - ZK_HOSTS=zookeeper:2181



volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
